apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
    ngress.kubernetes.io/rewrite-target: /
  name: hello-ingress
  namespace: default
spec:
  rules:
  - host: dashboard.skkim.me
    http:
      paths:
      - path: /
        backend:
          serviceName: dashboard-service
          servicePort: 8080